server:
  port: 8110
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  profiles:
    active: dev #开发环境
  application:
    name: service-core
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srb?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: abc123
  redis:
    host: 192.168.28.129
    database: 0
    timeout: 3000ms #最大等待时长
    lettuce:
      pool:
        max-active: 20 #最大连接数 负值表示没有限制 默认8
        max-wait: -1 #最大阻塞等待时长
        max-idle: 8 #最大空闲连接 默认8
        min-idle: 0 #最小空闲连接 默认0
mybatis-plus: #mybatis
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 mapper-locations: classpath:com/cx/srb/core/mapper/xml/*.xml