spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8130
oss:
  aliyun:
    endpoint: 
    access-key-id:
    access-key-secret:
    bucket-name:
