spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8130
oss:
  aliyun:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8CNiY2dDpKeWGsUE7s
    access-key-secret: ikYeYzM4zNdLsUUZe2Pv9PZOA8qh8e
    bucket-name: elden
