server:
  port: 8120
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: service-sms
  profiles:
    active: dev
  redis:
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-wait: -1
        max-active: 20
        max-idle: 8
        min-idle: 0
    host: 192.168.28.129
sms:
  txyun:
    sms-sdk-app-id:
    template-id:
    sign-name:
    region:
    secret-id:
    secret-key:

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 60000 #执行超时配置
  sentinel:
    enabled: true